---
- hosts: aws_ec2
  become: yes
  remote_user: ec2-user
  gather_facts: true

  vars:
    ansible_ssh_private_key_file: "/etc/ansible/teja.pem"
    ansible_ssh_user: "ec2-user"

  tasks:
    - name: install httpd
      action: yum name=httpd state=present
      
    - name: restart httpd
      service: name=httpd state=restarted
      
    - name: install git
      command: yum install git -y

    - name: get code from git
      git:
        repo: https://github.com/devops0014/devops-project-004.git
        dest: /var/www/html/index.html
        version: front
     

